# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# For more details, refer to the documentation:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build"
    target-branch: "dependabotchanges"
    open-pull-requests-limit: 10

 # Monitor .NET dependencies in .csproj files
  - package-ecosystem: "nuget"
    directory: "/App/backend-api/Microsoft.GS.DPS"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build"
    target-branch: "dependabotchanges"
    open-pull-requests-limit: 30

  - package-ecosystem: "nuget"
    directory: "/App/backend-api/Microsoft.GS.DPS.Host"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build"
    target-branch: "dependabotchanges"
    open-pull-requests-limit: 30


  # Kernel Memory Clients
  - package-ecosystem: "nuget"
    directory: "/App/kernel-memory/clients/dotnet/SemanticKernelPlugin"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build"
    target-branch: "dependabotchanges"
    open-pull-requests-limit: 30

  - package-ecosystem: "nuget"
    directory: "/App/kernel-memory/clients/dotnet/WebClient"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build"
    target-branch: "dependabotchanges"
    open-pull-requests-limit: 30

  # Kernel Memory Extensions
  - package-ecosystem: "nuget"
    directory: "/App/kernel-memory/extensions/Anthropic"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build"
    target-branch: "dependabotchanges"
    open-pull-requests-limit: 30

  - package-ecosystem: "nuget"
    directory: "/App/kernel-memory/extensions/AWS/S3"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build"
    target-branch: "dependabotchanges"
    open-pull-requests-limit: 30

  - package-ecosystem: "nuget"
    directory: "/App/kernel-memory/extensions/AzureAIDocIntel"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build"
    target-branch: "dependabotchanges"
    open-pull-requests-limit: 30

  - package-ecosystem: "nuget"
    directory: "/App/kernel-memory/extensions/AzureAISearch/AzureAISearch"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build"
    target-branch: "dependabotchanges"
    open-pull-requests-limit: 30

  - package-ecosystem: "nuget"
    directory: "/App/kernel-memory/extensions/AzureBlobs"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build"
    target-branch: "dependabotchanges"
    open-pull-requests-limit: 30

  - package-ecosystem: "nuget"
    directory: "/App/kernel-memory/extensions/AzureOpenAI"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build"
    target-branch: "dependabotchanges"
    open-pull-requests-limit: 30

  - package-ecosystem: "nuget"
    directory: "/App/kernel-memory/extensions/AzureQueues"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build"
    target-branch: "dependabotchanges"
    open-pull-requests-limit: 30

  - package-ecosystem: "nuget"
    directory: "/App/kernel-memory/extensions/Discord/Discord"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build"
    target-branch: "dependabotchanges"
    open-pull-requests-limit: 30

  - package-ecosystem: "nuget"
    directory: "/App/kernel-memory/extensions/Elasticsearch/Elasticsearch"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build"
    target-branch: "dependabotchanges"
    open-pull-requests-limit: 30

  - package-ecosystem: "nuget"
    directory: "/App/kernel-memory/extensions/LlamaSharp/LlamaSharp"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build"
    target-branch: "dependabotchanges"
    open-pull-requests-limit: 30

  - package-ecosystem: "nuget"
    directory: "/App/kernel-memory/extensions/MongoDbAtlas/MongoDbAtlas"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build"
    target-branch: "dependabotchanges"
    open-pull-requests-limit: 30

  - package-ecosystem: "nuget"
    directory: "/App/kernel-memory/extensions/OpenAI/OpenAI"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build"
    target-branch: "dependabotchanges"
    open-pull-requests-limit: 30

  - package-ecosystem: "nuget"
    directory: "/App/kernel-memory/extensions/Postgres/Postgres"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build"
    target-branch: "dependabotchanges"
    open-pull-requests-limit: 30

  - package-ecosystem: "nuget"
    directory: "/App/kernel-memory/extensions/Qdrant/Qdrant"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build"
    target-branch: "dependabotchanges"
    open-pull-requests-limit: 30

  - package-ecosystem: "nuget"
    directory: "/App/kernel-memory/extensions/Redis/Redis"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build"
    target-branch: "dependabotchanges"
    open-pull-requests-limit: 30

  - package-ecosystem: "nuget"
    directory: "/App/kernel-memory/extensions/SQLServer/SQLServer"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build"
    target-branch: "dependabotchanges"
    open-pull-requests-limit: 30

  # Kernel Memory Core Service
  - package-ecosystem: "nuget"
    directory: "/App/kernel-memory/service/Abstractions"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build"
    target-branch: "dependabotchanges"
    open-pull-requests-limit: 30

  - package-ecosystem: "nuget"
    directory: "/App/kernel-memory/service/Core"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build"
    target-branch: "dependabotchanges"
    open-pull-requests-limit: 30

  - package-ecosystem: "nuget"
    directory: "/App/kernel-memory/service/Service"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build"
    target-branch: "dependabotchanges"
    open-pull-requests-limit: 30

  - package-ecosystem: "nuget"
    directory: "/App/kernel-memory/service/Service.AspNetCore"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build"
    target-branch: "dependabotchanges"
    open-pull-requests-limit: 30

  # Monitor the nuget.config file
  - package-ecosystem: "nuget"
    directory: "/App/kernel-memory"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build"
    target-branch: "dependabotchanges"
    ignore:
      - dependency-name: "*"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build"
    target-branch: "dependabotchanges"
    open-pull-requests-limit: 30

  # .NET NuGet dependencies for Backend API (Multiple Projects)
  - package-ecosystem: "nuget"
    directory: "/App/backend-api/Microsoft.GS.DPS"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build"
    target-branch: "dependabotchanges"
    open-pull-requests-limit: 30

  - package-ecosystem: "nuget"
    directory: "/App/backend-api/Microsoft.GS.DPS.Host"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build"
    target-branch: "dependabotchanges"
    open-pull-requests-limit: 30

  # .NET NuGet dependencies for Kernel Memory Clients
  - package-ecosystem: "nuget"
    directory: "/App/kernel-memory/clients/dotnet/SemanticKernelPlugin"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build"
    target-branch: "dependabotchanges"
    open-pull-requests-limit: 30

  - package-ecosystem: "nuget"
    directory: "/App/kernel-memory/clients/dotnet/WebClient"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build"
    target-branch: "dependabotchanges"
    open-pull-requests-limit: 30

  # .NET NuGet dependencies for Kernel Memory Extensions
  - package-ecosystem: "nuget"
    directory: "/App/kernel-memory/extensions/Anthropic"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build"
    target-branch: "dependabotchanges"
    open-pull-requests-limit: 30

  - package-ecosystem: "nuget"
    directory: "/App/kernel-memory/extensions/AWS/S3"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build"
    target-branch: "dependabotchanges"
    open-pull-requests-limit: 30

  # npm dependencies for Frontend App
  - package-ecosystem: "npm"
    directory: "/App/frontend-app"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build"
    target-branch: "dependabotchanges"
    open-pull-requests-limit: 20
