apiVersion: v1
kind: Service
metadata:
  name: aiservice-service
  namespace: ns-km
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 9001
  selector:
    app: aiservice
---
apiVersion: v1
kind: Service
metadata:
  name: frontapp-service
  namespace: ns-km
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 5900
  selector:
    app: frontapp
