name: Deploy Resources

on:
  push:
    branches:
      - main  # Adjust this to the branch you want to trigger the deployment on
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  deploy:
    runs-on: windows-latest  # Use a Windows runner for PowerShell scripts

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3  # Checks out your repository

    - name: Setup PowerShell
      shell: pwsh
      run: |
        $PSVersionTable.PSVersion

    - name: Run Deployment Script with Input
      shell: pwsh
      run: |
        cd Deployment
        $input = @"
        ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        CanadaCentral
        WestUS3
        v-harmanprka@MngEnvMCAP993385.onmicrosoft.com
        yes
        "@
        $input | pwsh ./resourcedeployment.ps1
        echo "Resource Group Name is ${{ env.rg_name }}"
        echo "Kubernetes resource group are ${{ env.krg_name }}"
      env:
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  